server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.157:3306/easyBuy?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
    time-zone: Australia/Adelaide

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.easyBuy.domain
